set -g prefix `
unbind C-b
bind ` send-prefix

set -s escape-time 0

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on


set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "tmux.conf reloaded"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind \\ split-window -h   
bind - split-window -v 
unbind '"'
unbind %

## Plugins
set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-bold-status false
set -g @tmux-dotbar-bold-current-window true
set -g @tmux-dotbar-position top
set -g @tmux-dotbar-left "false"
set -g @tmux-dotbar-right "true"
set -g @tmux-dotbar-status-right "#{?client_prefix,#[bg=#fabd2f fg=default] #S ,#[fg=#928374] #S }"

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
